#!/bin/bash
# acme
# A container to issue and renew Let's Encrypt SSL certificates using acme-tiny.
#
# Copyright (c) 2021  SGS Serious Gaming & Simulations GmbH
#
# This work is licensed under the terms of the MIT license.
# For a copy, see LICENSE file or <https://opensource.org/licenses/MIT>.
#
# SPDX-License-Identifier: MIT
# License-Filename: LICENSE

set -eu -o pipefail
export LC_ALL=C.UTF-8

log() {
    printf "$1\n" "${@:2}" >&2
}

# create /var/local/acme skeleton, if necessary
if [ ! -d "/var/local/acme/live" ]; then
    log "creating directory '/var/local/acme/live'..."

    mkdir "/var/local/acme/live"
    chown acme:acme "/var/local/acme/live"
fi

if [ ! -d "/var/local/acme/archive" ]; then
    log "creating directory '/var/local/acme/archive'..."

    mkdir "/var/local/acme/archive"
    chown acme:acme "/var/local/acme/archive"
fi

if [ ! -d "/var/local/acme/challenges" ]; then
    log "creating directory '/var/local/acme/challenges'..."

    mkdir "/var/local/acme/challenges"
    chown acme:acme "/var/local/acme/challenges"
fi

# create account key, if necessary
if [ -z "${ACME_ACCOUNT_KEY_FILE:-}" ] || [ "$ACME_ACCOUNT_KEY_FILE" == "/etc/acme/account.key" ]; then
    if [ ! -f "/etc/acme/account.key" ]; then
        log "creating account key '/etc/acme/account.key'..."

        ( umask 027 && openssl genrsa 4096 > "/etc/acme/account.key" )
        chmod 640 "/etc/acme/account.key"
        chown acme:acme "/etc/acme/account.key"
    fi
fi

# create acme config file, if necessary
if [ ! -f "/etc/acme/config.env" ]; then
    __config_set() {
        local NAME="$1"
        local VALUE="$2"

        log "updating runtime config: $NAME=${VALUE@Q}"
        sed -i "/^#$NAME=/a $NAME=$(sed -e 's/\\/\\\\/g' <<< "${VALUE@Q}")" "/etc/acme/config.env"
    }

    log "creating config file '/etc/acme/config.env'..."

    cp "/usr/local/share/acme/config.env" "/etc/acme/config.env"
    chown acme:acme "/etc/acme/config.env"

    [ "${ACME_ACCOUNT_KEY_FILE:-}" != "/etc/acme/account.key" ] || unset ACME_ACCOUNT_KEY_FILE

    [ -z "${ACME_ACCOUNT_KEY_FILE:-}" ] || __config_set ACME_ACCOUNT_KEY_FILE "$ACME_ACCOUNT_KEY_FILE"
    [ -z "${ACME_ACCOUNT_CONTACT:-}" ] || __config_set ACME_ACCOUNT_CONTACT "$ACME_ACCOUNT_CONTACT"
    [ -z "${ACME_DIRECTORY_URL:-}" ] || __config_set ACME_DIRECTORY_URL "$ACME_DIRECTORY_URL"
    [ -z "${TLS_KEY_GROUP:-}" ] || __config_set TLS_KEY_GROUP "$TLS_KEY_GROUP"
    [ -z "${FP_REVOCATION_LIST:-}" ] || __config_set FP_REVOCATION_LIST "$FP_REVOCATION_LIST"
fi

# create crontab file, if necessary
if [ ! -f "/etc/crontabs/acme" ]; then
    __is_cron_valid() {
        [ -n "$1" ] && [[ "$1 " =~ ^(((\d+|\*)(/\d+)?|\d+-\d+)(,((\d+|\*)(/\d+)?|\d+-\d+))* ){5}$ ]]
    }

    __crontabs() {
        local HASH="$(md5sum - <<< "$1")"
        shift

        # TIME represents the `n`th minute of the month (e.g., 12,345 is the 9th day at 13:45)
        # since the cronjob wouldn't run in February otherwise, we accept the 28th day max,
        # thus we perform an euclidean division by 28 days * 24 hours * 60 minutes = 40,320
        # day of month, weekday, hour, and minute are whole dividers and thus derived directly
        local TIME=$(( 0x${HASH:0:14} % 40320 ))

        # TIME_MONTH represents the `n`th month of the year (e.g., 3 is March)
        # thus we perform an euclidean division by 12 (months)
        local TIME_MONTH=$(( 0x${HASH:14:4} % 12 + 1 ))

        # MULTI_JOB_OFFSET is used to offset the execution time ob multiple cronjobs
        # all cronjobs shall run between 10 and 20 minutes after each other,
        # thus we perform an euclidean division by 10 minutes and add another 10 minutes
        # we use Bash's pseudo random number generator and seed it by an incrementing
        # MULTI_JOB_SEED to calculate (pseudo) random, but stable per-cronjob offsets
        local MULTI_JOB_OFFSET=0 MULTI_JOB_SEED=$(( 0x${HASH:18:4} ))

        local CRON_TIME= CRON_MONTH= CRON_DAY= CRON_WEEKDAY= CRON_HOUR= CRON_MINUTE=
        while (( $# >= 2 )); do
            if __is_cron_valid "$1"; then
                printf '%s %s\n' "$1" "$2"
            elif [[ "$1" =~ ^@(yearly|monthly|weekly|daily|hourly)$ ]]; then
                CRON_TIME=$(( TIME + MULTI_JOB_OFFSET ))
                CRON_MONTH="*"; CRON_DAY="*"; CRON_WEEKDAY="*"; CRON_HOUR="*"
                [ "$1" != "@yearly" ] || CRON_MONTH=$TIME_MONTH
                [ "$1" != "@monthly" ] || CRON_DAY=$(( CRON_TIME / 1440 + 1 ))
                [ "$1" != "@weekly" ] || CRON_WEEKDAY=$(( CRON_TIME % 10080 / 1440 ))
                [ "$1" == "@hourly" ] || CRON_HOUR=$(( CRON_TIME % 1440 / 60 ))
                CRON_MINUTE=$(( CRON_TIME % 60 ))

                printf '%s %s %s %s %s %s\n' "$CRON_MINUTE" "$CRON_HOUR" "$CRON_DAY" "$CRON_MONTH" "$CRON_WEEKDAY" "$2"

                MULTI_JOB_SEED=$(( ++MULTI_JOB_SEED % 32768 ))
                (( MULTI_JOB_OFFSET += $(bash -c "RANDOM=$MULTI_JOB_SEED; echo \$RANDOM") % 10 + 10 ))
            else
                echo "Invalid crontab: $1 $2" >&2
                return 1
            fi
            shift 2
        done
    }

    log "creating crontab file '/etc/crontabs/acme'..."

    __crontabs "$(ls -1 "/var/local/acme/live")" \
        "${CRON_RENEW:-@monthly}" "acme-renew --all --retry --retry --clean --verbose" \
        "${CRON_CHECK:-@daily}" "acme-check --all --retry --retry --renew --retry-renew --retry-renew --verbose" \
        > "/etc/crontabs/acme"
fi
